spring.application.name=api-google-calendar
spring.profiles.active=dev

# A sua chave de producao vai aqui quando for feito o deploy.
# Para testes locais, o Spring vai ler o application-dev.properties (que ja esta no .gitignore!)
google.api.key=${GOOGLE_API_KEY:coloque_sua_chave_aqui}